const express = require("express");
const router = express.Router();
const shareController = require("../../controllers/share/share");
const guessController = require("../../controllers/share/guess");
const getUserId = require("../../controllers/share/getUserId");
const serverAccessToken = require("../../middleware/serverAccess");
router.get("/:id", shareController);
router.post("/:id/guess", guessController);
router.get("/getUserId/:id", getUserId);
module.exports = router;
